PRAGMA synchronous = OFF;
PRAGMA journal_mode = OFF;
BEGIN EXCLUSIVE TRANSACTION;
PRAGMA defer_foreign_keys = ON;
UPDATE collection_categories SET name='ABC' WHERE id=1;
UPDATE collection_categories SET name='DEF' WHERE id=2;
UPDATE collection_categories SET name='GHI' WHERE id=3;
UPDATE collection_categories SET name='JKL' WHERE id=4;
UPDATE collection_categories SET name='MNO' WHERE id=5;
UPDATE collection_categories SET name='PQR' WHERE id=6;
UPDATE collection_categories SET name='STU' WHERE id=7;
UPDATE collection_categories SET name='VWX' WHERE id=8;
UPDATE collection_categories SET name='YZ' WHERE id=9;
UPDATE collection_uniques SET priority=64 WHERE id=1;
UPDATE collection_uniques SET collection_category_id=8, priority=1 WHERE id=2;
UPDATE collection_uniques SET collection_category_id=7, priority=1 WHERE id=3;
UPDATE collection_uniques SET collection_category_id=6, priority=11 WHERE id=4;
UPDATE collection_uniques SET priority=1 WHERE id=5;
UPDATE collection_uniques SET collection_category_id=5, priority=44 WHERE id=6;
UPDATE collection_uniques SET collection_category_id=5, priority=30 WHERE id=7;
UPDATE collection_uniques SET collection_category_id=5, priority=29 WHERE id=8;
UPDATE collection_uniques SET collection_category_id=4, priority=13 WHERE id=9;
UPDATE collection_uniques SET collection_category_id=1, priority=25 WHERE id=10;
UPDATE collection_uniques SET collection_category_id=1, priority=5 WHERE id=12;
UPDATE collection_uniques SET collection_category_id=4, priority=8 WHERE id=13;
UPDATE collection_uniques SET collection_category_id=4, priority=7 WHERE id=14;
UPDATE collection_uniques SET collection_category_id=3, priority=12 WHERE id=15;
UPDATE collection_uniques SET collection_category_id=3, priority=33 WHERE id=16;
UPDATE collection_uniques SET collection_category_id=3, priority=35 WHERE id=17;
UPDATE collection_uniques SET collection_category_id=4, priority=11 WHERE id=18;
UPDATE collection_uniques SET collection_category_id=9, priority=1 WHERE id=19;
UPDATE collection_uniques SET collection_category_id=7, priority=134 WHERE id=20;
UPDATE collection_uniques SET collection_category_id=1, priority=3 WHERE id=21;
UPDATE collection_uniques SET collection_category_id=9, priority=2 WHERE id=22;
UPDATE collection_uniques SET collection_category_id=4, priority=22 WHERE id=23;
UPDATE collection_uniques SET collection_category_id=7, priority=130 WHERE id=24;
UPDATE collection_uniques SET collection_category_id=7, priority=129 WHERE id=25;
UPDATE collection_uniques SET collection_category_id=4, priority=25 WHERE id=26;
UPDATE collection_uniques SET collection_category_id=4, priority=26 WHERE id=27;
UPDATE collection_uniques SET collection_category_id=4, priority=21 WHERE id=28;
UPDATE collection_uniques SET collection_category_id=1, priority=180 WHERE id=29;
UPDATE collection_uniques SET collection_category_id=1, priority=170 WHERE id=32;
UPDATE collection_uniques SET collection_category_id=1, priority=160 WHERE id=33;
UPDATE collection_uniques SET collection_category_id=1, priority=150 WHERE id=34;
UPDATE collection_uniques SET collection_category_id=1, priority=140 WHERE id=35;
UPDATE collection_uniques SET collection_category_id=1, priority=130 WHERE id=36;
UPDATE collection_uniques SET collection_category_id=1, priority=110 WHERE id=37;
UPDATE collection_uniques SET collection_category_id=1, priority=1 WHERE id=38;
UPDATE collection_uniques SET collection_category_id=7, priority=51 WHERE id=39;
UPDATE collection_uniques SET collection_category_id=7, priority=85 WHERE id=40;
UPDATE collection_uniques SET collection_category_id=7, priority=65 WHERE id=41;
UPDATE collection_uniques SET collection_category_id=7, priority=57 WHERE id=42;
UPDATE collection_uniques SET collection_category_id=7, priority=46 WHERE id=43;
UPDATE collection_uniques SET collection_category_id=7, priority=52 WHERE id=44;
UPDATE collection_uniques SET collection_category_id=7, priority=86 WHERE id=45;
UPDATE collection_uniques SET collection_category_id=7, priority=53 WHERE id=46;
UPDATE collection_uniques SET collection_category_id=7, priority=44 WHERE id=47;
UPDATE collection_uniques SET collection_category_id=7, priority=43 WHERE id=48;
UPDATE collection_uniques SET collection_category_id=7, priority=41 WHERE id=49;
UPDATE collection_uniques SET collection_category_id=7, priority=60 WHERE id=50;
UPDATE collection_uniques SET collection_category_id=7, priority=42 WHERE id=51;
UPDATE collection_uniques SET collection_category_id=7, priority=78 WHERE id=52;
UPDATE collection_uniques SET collection_category_id=7, priority=55 WHERE id=53;
UPDATE collection_uniques SET collection_category_id=7, priority=124 WHERE id=54;
UPDATE collection_uniques SET collection_category_id=2, priority=19 WHERE id=55;
UPDATE collection_uniques SET collection_category_id=1, priority=21 WHERE id=56;
UPDATE collection_uniques SET collection_category_id=1, priority=20 WHERE id=57;
UPDATE collection_uniques SET collection_category_id=1, priority=19 WHERE id=58;
UPDATE collection_uniques SET collection_category_id=7, priority=126 WHERE id=59;
UPDATE collection_uniques SET priority=56 WHERE id=60;
UPDATE collection_uniques SET priority=52 WHERE id=61;
UPDATE collection_uniques SET priority=50 WHERE id=62;
UPDATE collection_uniques SET priority=30 WHERE id=63;
UPDATE collection_uniques SET priority=64 WHERE id=65;
UPDATE collection_uniques SET priority=63 WHERE id=66;
UPDATE collection_uniques SET priority=62 WHERE id=67;
UPDATE collection_uniques SET collection_category_id=2, priority=43 WHERE id=68;
UPDATE collection_uniques SET collection_category_id=5, priority=24 WHERE id=69;
UPDATE collection_uniques SET collection_category_id=7, priority=32 WHERE id=70;
UPDATE collection_uniques SET collection_category_id=7, priority=31 WHERE id=71;
UPDATE collection_uniques SET collection_category_id=1, priority=13 WHERE id=72;
UPDATE collection_uniques SET collection_category_id=1, priority=12 WHERE id=73;
UPDATE collection_uniques SET collection_category_id=1, priority=10 WHERE id=74;
UPDATE collection_uniques SET collection_category_id=1, priority=9 WHERE id=75;
UPDATE collection_uniques SET collection_category_id=5, priority=27 WHERE id=76;
UPDATE collection_uniques SET collection_category_id=7, priority=23 WHERE id=77;
UPDATE collection_uniques SET collection_category_id=7, priority=19 WHERE id=78;
UPDATE collection_uniques SET collection_category_id=2, priority=32 WHERE id=79;
UPDATE collection_uniques SET collection_category_id=1, priority=45 WHERE id=80;
UPDATE collection_uniques SET collection_category_id=2, priority=34 WHERE id=81;
UPDATE collection_uniques SET collection_category_id=2, priority=28 WHERE id=82;
UPDATE collection_uniques SET collection_category_id=7, priority=13 WHERE id=83;
UPDATE collection_uniques SET collection_category_id=7, priority=11 WHERE id=84;
UPDATE collection_uniques SET collection_category_id=7, priority=15 WHERE id=85;
UPDATE collection_uniques SET priority=10 WHERE id=86;
UPDATE collection_uniques SET priority=13 WHERE id=87;
UPDATE collection_uniques SET collection_category_id=1, priority=31 WHERE id=88;
UPDATE collection_uniques SET collection_category_id=1, priority=55 WHERE id=89;
UPDATE collection_uniques SET priority=18 WHERE id=90;
UPDATE collection_uniques SET priority=27 WHERE id=91;
UPDATE collection_uniques SET collection_category_id=1, priority=62 WHERE id=92;
UPDATE collection_uniques SET collection_category_id=1, priority=61 WHERE id=93;
UPDATE collection_uniques SET collection_category_id=7, priority=128 WHERE id=94;
UPDATE collection_uniques SET collection_category_id=8, priority=4 WHERE id=95;
UPDATE collection_uniques SET priority=16 WHERE id=96;
UPDATE collection_uniques SET collection_category_id=1, priority=48 WHERE id=97;
UPDATE collection_uniques SET collection_category_id=1, priority=51 WHERE id=98;
UPDATE collection_uniques SET priority=10 WHERE id=99;
UPDATE collection_uniques SET collection_category_id=1, priority=37 WHERE id=100;
UPDATE collection_uniques SET collection_category_id=2, priority=17 WHERE id=101;
UPDATE collection_uniques SET collection_category_id=2, priority=16 WHERE id=102;
UPDATE collection_uniques SET collection_category_id=2, priority=15 WHERE id=103;
UPDATE collection_uniques SET collection_category_id=2, priority=14 WHERE id=104;
UPDATE collection_uniques SET collection_category_id=2, priority=10 WHERE id=105;
UPDATE collection_uniques SET collection_category_id=2, priority=4 WHERE id=107;
UPDATE collection_uniques SET priority=12 WHERE id=108;
UPDATE collection_uniques SET collection_category_id=8, priority=14 WHERE id=109;
UPDATE collection_uniques SET collection_category_id=8, priority=10 WHERE id=110;
UPDATE collection_uniques SET collection_category_id=4, priority=9 WHERE id=111;
UPDATE collection_uniques SET collection_category_id=1, priority=41 WHERE id=112;
UPDATE collection_uniques SET collection_category_id=5, priority=20 WHERE id=113;
UPDATE collection_uniques SET collection_category_id=6, priority=15 WHERE id=114;
UPDATE collection_uniques SET collection_category_id=1, priority=16 WHERE id=115;
UPDATE collection_uniques SET collection_category_id=1, priority=28 WHERE id=116;
UPDATE collection_uniques SET collection_category_id=5, priority=38 WHERE id=117;
UPDATE collection_uniques SET collection_category_id=5, priority=41 WHERE id=118;
UPDATE collection_uniques SET collection_category_id=5, priority=34 WHERE id=119;
UPDATE collection_uniques SET collection_category_id=3, priority=7 WHERE id=120;
UPDATE collection_uniques SET collection_category_id=5, priority=26 WHERE id=122;
UPDATE collection_uniques SET collection_category_id=9, priority=8 WHERE id=123;
UPDATE collection_uniques SET collection_category_id=9, priority=9 WHERE id=124;
UPDATE collection_uniques SET collection_category_id=9, priority=5 WHERE id=125;
UPDATE collection_uniques SET collection_category_id=9, priority=7 WHERE id=126;
UPDATE collection_uniques SET collection_category_id=6, priority=9 WHERE id=127;
UPDATE collection_uniques SET collection_category_id=6, priority=4 WHERE id=128;
UPDATE collection_uniques SET collection_category_id=6, priority=3 WHERE id=129;
UPDATE collection_uniques SET collection_category_id=1, priority=8 WHERE id=130;
UPDATE collection_uniques SET collection_category_id=1, priority=7 WHERE id=131;
UPDATE collection_uniques SET collection_category_id=7, priority=25 WHERE id=132;
UPDATE collection_uniques SET collection_category_id=2, priority=33 WHERE id=133;
UPDATE collection_uniques SET priority=12 WHERE id=134;
UPDATE collection_uniques SET collection_category_id=3, priority=16 WHERE id=135;
UPDATE collection_uniques SET collection_category_id=3, priority=13 WHERE id=136;
UPDATE collection_uniques SET collection_category_id=7, priority=3 WHERE id=137;
UPDATE collection_uniques SET collection_category_id=1, priority=30 WHERE id=138;
UPDATE collection_uniques SET collection_category_id=1, priority=35 WHERE id=139;
UPDATE collection_uniques SET collection_category_id=4, priority=6 WHERE id=140;
UPDATE collection_uniques SET collection_category_id=3, priority=5 WHERE id=141;
UPDATE collection_uniques SET collection_category_id=5, priority=16 WHERE id=142;
UPDATE collection_uniques SET collection_category_id=7, priority=109 WHERE id=143;
UPDATE collection_uniques SET priority=53 WHERE id=144;
UPDATE collection_uniques SET collection_category_id=7, priority=5 WHERE id=145;
UPDATE collection_uniques SET collection_category_id=1, priority=26 WHERE id=146;
UPDATE collection_uniques SET collection_category_id=2, priority=42 WHERE id=147;
UPDATE collection_uniques SET priority=190 WHERE id=148;
UPDATE collection_uniques SET collection_category_id=6, priority=5 WHERE id=149;
UPDATE collection_uniques SET collection_category_id=4, priority=5 WHERE id=150;
UPDATE collection_uniques SET priority=55 WHERE id=151;
UPDATE collection_uniques SET priority=25 WHERE id=152;
UPDATE collection_uniques SET collection_category_id=7, priority=102 WHERE id=153;
UPDATE collection_uniques SET collection_category_id=7, priority=96 WHERE id=154;
UPDATE collection_uniques SET collection_category_id=5, priority=33 WHERE id=155;
UPDATE collection_uniques SET collection_category_id=8, priority=12 WHERE id=156;
UPDATE collection_uniques SET collection_category_id=7, priority=105 WHERE id=157;
UPDATE collection_uniques SET collection_category_id=3, priority=6 WHERE id=158;
UPDATE collection_uniques SET priority=19 WHERE id=159;
UPDATE collection_uniques SET collection_category_id=2, priority=36 WHERE id=160;
UPDATE collection_uniques SET collection_category_id=2, priority=37 WHERE id=161;
UPDATE collection_uniques SET collection_category_id=2, priority=35 WHERE id=162;
UPDATE collection_uniques SET collection_category_id=5, priority=2 WHERE id=163;
UPDATE collection_uniques SET priority=12 WHERE id=164;
UPDATE collection_uniques SET collection_category_id=2, priority=30 WHERE id=165;
UPDATE collection_uniques SET collection_category_id=1, priority=56 WHERE id=166;
UPDATE collection_uniques SET collection_category_id=5, priority=15 WHERE id=167;
UPDATE collection_uniques SET collection_category_id=3, priority=72 WHERE id=168;
UPDATE collection_uniques SET collection_category_id=1, priority=34 WHERE id=169;
UPDATE collection_uniques SET collection_category_id=2, priority=22 WHERE id=170;
UPDATE collection_uniques SET collection_category_id=8, priority=7 WHERE id=171;
UPDATE collection_uniques SET priority=23 WHERE id=172;
UPDATE collection_uniques SET collection_category_id=5, priority=39 WHERE id=173;
UPDATE collection_uniques SET collection_category_id=1, priority=39 WHERE id=174;
UPDATE collection_uniques SET collection_category_id=7, priority=59 WHERE id=175;
UPDATE collection_uniques SET priority=3 WHERE id=176;
UPDATE collection_uniques SET priority=21 WHERE id=177;
UPDATE collection_uniques SET collection_category_id=7, priority=36 WHERE id=178;
UPDATE collection_uniques SET collection_category_id=5, priority=22 WHERE id=179;
UPDATE collection_uniques SET collection_category_id=1, priority=2 WHERE id=180;
UPDATE collection_uniques SET collection_category_id=7, priority=40 WHERE id=181;
UPDATE collection_uniques SET collection_category_id=3, priority=28 WHERE id=182;
UPDATE collection_uniques SET collection_category_id=1, priority=33 WHERE id=183;
UPDATE collection_uniques SET collection_category_id=4, priority=4 WHERE id=184;
UPDATE collection_uniques SET collection_category_id=7, priority=123 WHERE id=185;
UPDATE collection_uniques SET collection_category_id=3, priority=68 WHERE id=186;
UPDATE collection_uniques SET collection_category_id=3, priority=27 WHERE id=187;
UPDATE collection_uniques SET collection_category_id=3, priority=26 WHERE id=188;
UPDATE collection_uniques SET collection_category_id=7, priority=2 WHERE id=189;
UPDATE collection_uniques SET collection_category_id=4, priority=15 WHERE id=190;
UPDATE collection_uniques SET collection_category_id=7, priority=87 WHERE id=191;
UPDATE collection_uniques SET collection_category_id=2, priority=31 WHERE id=192;
UPDATE collection_uniques SET collection_category_id=3, priority=10 WHERE id=193;
UPDATE collection_uniques SET collection_category_id=7, priority=103 WHERE id=194;
UPDATE collection_uniques SET collection_category_id=7, priority=68 WHERE id=195;
UPDATE collection_uniques SET collection_category_id=4, priority=14 WHERE id=196;
UPDATE collection_uniques SET collection_category_id=8, priority=5 WHERE id=197;
UPDATE collection_uniques SET collection_category_id=7, priority=116 WHERE id=198;
UPDATE collection_uniques SET collection_category_id=7, priority=115 WHERE id=199;
UPDATE collection_uniques SET collection_category_id=7, priority=100 WHERE id=200;
UPDATE collection_uniques SET collection_category_id=4, priority=17 WHERE id=201;
UPDATE collection_uniques SET priority=11 WHERE id=202;
UPDATE collection_uniques SET collection_category_id=1, priority=57 WHERE id=203;
UPDATE collection_uniques SET collection_category_id=7, priority=93 WHERE id=204;
UPDATE collection_uniques SET collection_category_id=7, priority=17 WHERE id=205;
UPDATE collection_uniques SET collection_category_id=5, priority=18 WHERE id=206;
UPDATE collection_uniques SET collection_category_id=2, priority=39 WHERE id=207;
UPDATE collection_uniques SET collection_category_id=7, priority=95 WHERE id=208;
UPDATE collection_uniques SET collection_category_id=7, priority=35 WHERE id=209;
UPDATE collection_uniques SET collection_category_id=7, priority=10 WHERE id=210;
UPDATE collection_uniques SET collection_category_id=7, priority=106 WHERE id=211;
UPDATE collection_uniques SET priority=65 WHERE id=212;
UPDATE collection_uniques SET collection_category_id=7, priority=97 WHERE id=213;
UPDATE collection_uniques SET collection_category_id=2, priority=11 WHERE id=214;
UPDATE collection_uniques SET collection_category_id=7, priority=37 WHERE id=215;
UPDATE collection_uniques SET collection_category_id=5, priority=14 WHERE id=216;
UPDATE collection_uniques SET collection_category_id=3, priority=70 WHERE id=217;
UPDATE collection_uniques SET collection_category_id=7, priority=83 WHERE id=218;
UPDATE collection_uniques SET collection_category_id=5, priority=23 WHERE id=219;
UPDATE collection_uniques SET collection_category_id=1, priority=60 WHERE id=220;
UPDATE collection_uniques SET collection_category_id=3, priority=71 WHERE id=221;
UPDATE collection_uniques SET collection_category_id=3, priority=2 WHERE id=222;
UPDATE collection_uniques SET collection_category_id=7, priority=84 WHERE id=223;
UPDATE collection_uniques SET collection_category_id=5, priority=40 WHERE id=224;
UPDATE collection_uniques SET collection_category_id=3, priority=15 WHERE id=225;
UPDATE collection_uniques SET collection_category_id=7, priority=80 WHERE id=226;
UPDATE collection_uniques SET priority=9 WHERE id=227;
UPDATE collection_uniques SET priority=49 WHERE id=228;
UPDATE collection_uniques SET collection_category_id=8, priority=11 WHERE id=229;
UPDATE collection_uniques SET collection_category_id=6, priority=8 WHERE id=230;
UPDATE collection_uniques SET collection_category_id=7, priority=28 WHERE id=231;
UPDATE collection_uniques SET collection_category_id=7, priority=94 WHERE id=232;
UPDATE collection_uniques SET collection_category_id=3, priority=20 WHERE id=233;
UPDATE collection_uniques SET collection_category_id=7, priority=120 WHERE id=234;
UPDATE collection_uniques SET collection_category_id=7, priority=73 WHERE id=235;
UPDATE collection_uniques SET priority=60 WHERE id=236;
UPDATE collection_uniques SET priority=31 WHERE id=237;
UPDATE collection_uniques SET priority=29 WHERE id=238;
UPDATE collection_uniques SET collection_category_id=7, priority=136 WHERE id=239;
UPDATE collection_uniques SET collection_category_id=1, priority=58 WHERE id=240;
UPDATE collection_uniques SET collection_category_id=1, priority=54 WHERE id=241;
UPDATE collection_uniques SET collection_category_id=2, priority=18 WHERE id=242;
UPDATE collection_uniques SET collection_category_id=7, priority=127 WHERE id=243;
UPDATE collection_uniques SET collection_category_id=1, priority=44 WHERE id=244;
UPDATE collection_uniques SET collection_category_id=7, priority=18 WHERE id=245;
UPDATE collection_uniques SET collection_category_id=7, priority=38 WHERE id=246;
UPDATE collection_uniques SET collection_category_id=6, priority=14 WHERE id=247;
UPDATE collection_uniques SET priority=24 WHERE id=248;
UPDATE collection_uniques SET collection_category_id=3, priority=4 WHERE id=249;
UPDATE collection_uniques SET collection_category_id=1, priority=42 WHERE id=250;
UPDATE collection_uniques SET collection_category_id=5, priority=43 WHERE id=251;
UPDATE collection_uniques SET collection_category_id=2, priority=7 WHERE id=252;
UPDATE collection_uniques SET collection_category_id=1, priority=27 WHERE id=253;
UPDATE collection_uniques SET collection_category_id=7, priority=111 WHERE id=254;
UPDATE collection_uniques SET collection_category_id=7, priority=71 WHERE id=255;
UPDATE collection_uniques SET name='Tiencha', priority=17 WHERE id=256;
UPDATE collection_uniques SET collection_category_id=1, priority=14 WHERE id=257;
UPDATE collection_uniques SET collection_category_id=2, priority=9 WHERE id=258;
UPDATE collection_uniques SET collection_category_id=2, priority=8 WHERE id=259;
UPDATE collection_uniques SET collection_category_id=4, priority=16 WHERE id=260;
UPDATE collection_uniques SET collection_category_id=1, priority=6 WHERE id=261;
UPDATE collection_uniques SET priority=22 WHERE id=262;
UPDATE collection_uniques SET collection_category_id=1, priority=53 WHERE id=263;
UPDATE collection_uniques SET collection_category_id=1, priority=11 WHERE id=264;
UPDATE collection_uniques SET collection_category_id=1, priority=32 WHERE id=265;
UPDATE collection_uniques SET collection_category_id=4, priority=23 WHERE id=266;
UPDATE collection_uniques SET collection_category_id=5, priority=35 WHERE id=267;
UPDATE collection_uniques SET collection_category_id=5, priority=36 WHERE id=268;
UPDATE collection_uniques SET collection_category_id=7, priority=4 WHERE id=269;
UPDATE collection_uniques SET collection_category_id=1, priority=66 WHERE id=270;
UPDATE collection_uniques SET collection_category_id=3, priority=25 WHERE id=271;
UPDATE collection_uniques SET collection_category_id=7, priority=98 WHERE id=272;
UPDATE collection_uniques SET collection_category_id=7, priority=113 WHERE id=273;
UPDATE collection_uniques SET collection_category_id=1, priority=59 WHERE id=274;
UPDATE collection_uniques SET collection_category_id=1, priority=29 WHERE id=275;
UPDATE collection_uniques SET collection_category_id=5, priority=3 WHERE id=276;
UPDATE collection_uniques SET collection_category_id=7, priority=33 WHERE id=277;
UPDATE collection_uniques SET collection_category_id=3, priority=9 WHERE id=278;
UPDATE collection_uniques SET collection_category_id=2, priority=23 WHERE id=279;
UPDATE collection_uniques SET collection_category_id=5, priority=7 WHERE id=280;
UPDATE collection_uniques SET collection_category_id=6, priority=7 WHERE id=281;
UPDATE collection_uniques SET collection_category_id=5, priority=5 WHERE id=282;
UPDATE collection_uniques SET collection_category_id=5, priority=8 WHERE id=283;
UPDATE collection_uniques SET collection_category_id=7, priority=67 WHERE id=284;
UPDATE collection_uniques SET collection_category_id=7, priority=26 WHERE id=285;
UPDATE collection_uniques SET priority=13 WHERE id=286;
UPDATE collection_uniques SET collection_category_id=3, priority=40 WHERE id=287;
UPDATE collection_uniques SET collection_category_id=1, priority=63 WHERE id=288;
UPDATE collection_uniques SET collection_category_id=5, priority=6 WHERE id=289;
UPDATE collection_uniques SET collection_category_id=7, priority=125 WHERE id=290;
UPDATE collection_uniques SET collection_category_id=7, priority=54 WHERE id=291;
UPDATE collection_uniques SET collection_category_id=3, priority=39 WHERE id=292;
UPDATE collection_uniques SET collection_category_id=7, priority=12 WHERE id=293;
UPDATE collection_uniques SET collection_category_id=5, priority=42 WHERE id=294;
UPDATE collection_uniques SET collection_category_id=9, priority=3 WHERE id=295;
UPDATE collection_uniques SET collection_category_id=5, priority=28 WHERE id=296;
UPDATE collection_uniques SET priority=2 WHERE id=297;
UPDATE collection_uniques SET collection_category_id=7, priority=62 WHERE id=298;
UPDATE collection_uniques SET collection_category_id=7, priority=61 WHERE id=299;
UPDATE collection_uniques SET collection_category_id=7, priority=64 WHERE id=300;
UPDATE collection_uniques SET collection_category_id=7, priority=119 WHERE id=301;
UPDATE collection_uniques SET collection_category_id=7, priority=121 WHERE id=302;
UPDATE collection_uniques SET priority=61 WHERE id=303;
UPDATE collection_uniques SET collection_category_id=7, priority=137 WHERE id=304;
UPDATE collection_uniques SET collection_category_id=7, priority=9 WHERE id=305;
UPDATE collection_uniques SET collection_category_id=7, priority=135 WHERE id=306;
UPDATE collection_uniques SET collection_category_id=1, priority=24 WHERE id=307;
UPDATE collection_uniques SET collection_category_id=7, priority=74 WHERE id=308;
UPDATE collection_uniques SET collection_category_id=5, priority=31 WHERE id=309;
UPDATE collection_uniques SET collection_category_id=7, priority=91 WHERE id=310;
UPDATE collection_uniques SET collection_category_id=5, priority=17 WHERE id=311;
UPDATE collection_uniques SET collection_category_id=3, priority=8 WHERE id=312;
UPDATE collection_uniques SET collection_category_id=7, priority=122 WHERE id=313;
UPDATE collection_uniques SET collection_category_id=4, priority=24 WHERE id=314;
UPDATE collection_uniques SET priority=36 WHERE id=315;
UPDATE collection_uniques SET collection_category_id=7, priority=101 WHERE id=316;
UPDATE collection_uniques SET collection_category_id=7, priority=70 WHERE id=317;
UPDATE collection_uniques SET collection_category_id=1, priority=47 WHERE id=318;
UPDATE collection_uniques SET collection_category_id=3, priority=37 WHERE id=319;
UPDATE collection_uniques SET collection_category_id=3, priority=38 WHERE id=320;
UPDATE collection_uniques SET collection_category_id=7, priority=76 WHERE id=321;
UPDATE collection_uniques SET collection_category_id=7, priority=50 WHERE id=322;
UPDATE collection_uniques SET priority=17 WHERE id=323;
UPDATE collection_uniques SET collection_category_id=2, priority=13 WHERE id=324;
UPDATE collection_uniques SET collection_category_id=4, priority=10 WHERE id=325;
UPDATE collection_uniques SET collection_category_id=7, priority=89 WHERE id=326;
UPDATE collection_uniques SET collection_category_id=4, priority=18 WHERE id=327;
UPDATE collection_uniques SET collection_category_id=7, priority=63 WHERE id=328;
UPDATE collection_uniques SET collection_category_id=8, priority=2 WHERE id=329;
UPDATE collection_uniques SET collection_category_id=1, priority=15 WHERE id=330;
UPDATE collection_uniques SET collection_category_id=7, priority=7 WHERE id=331;
UPDATE collection_uniques SET collection_category_id=6, priority=6 WHERE id=332;
UPDATE collection_uniques SET collection_category_id=1, priority=49 WHERE id=333;
UPDATE collection_uniques SET collection_category_id=5, priority=37 WHERE id=334;
UPDATE collection_uniques SET collection_category_id=7, priority=21 WHERE id=335;
UPDATE collection_uniques SET collection_category_id=3, priority=32 WHERE id=336;
UPDATE collection_uniques SET collection_category_id=9, priority=4 WHERE id=337;
UPDATE collection_uniques SET priority=51 WHERE id=338;
UPDATE collection_uniques SET collection_category_id=2, priority=3 WHERE id=339;
UPDATE collection_uniques SET collection_category_id=3, priority=21 WHERE id=340;
UPDATE collection_uniques SET collection_category_id=8, priority=6 WHERE id=341;
UPDATE collection_uniques SET collection_category_id=7, priority=45 WHERE id=342;
UPDATE collection_uniques SET collection_category_id=2, priority=40 WHERE id=343;
UPDATE collection_uniques SET collection_category_id=7, priority=69 WHERE id=344;
UPDATE collection_uniques SET collection_category_id=7, priority=75 WHERE id=345;
UPDATE collection_uniques SET collection_category_id=7, priority=22 WHERE id=346;
UPDATE collection_uniques SET collection_category_id=5, priority=32 WHERE id=347;
UPDATE collection_uniques SET priority=26 WHERE id=348;
UPDATE collection_uniques SET collection_category_id=7, priority=79 WHERE id=349;
UPDATE collection_uniques SET collection_category_id=7, priority=77 WHERE id=350;
UPDATE collection_uniques SET collection_category_id=7, priority=29 WHERE id=351;
UPDATE collection_uniques SET collection_category_id=7, priority=30 WHERE id=352;
UPDATE collection_uniques SET collection_category_id=3, priority=3 WHERE id=353;
UPDATE collection_uniques SET collection_category_id=5, priority=19 WHERE id=354;
UPDATE collection_uniques SET priority=48 WHERE id=355;
UPDATE collection_uniques SET collection_category_id=7, priority=49 WHERE id=356;
UPDATE collection_uniques SET priority=46 WHERE id=357;
UPDATE collection_uniques SET collection_category_id=7, priority=48 WHERE id=358;
UPDATE collection_uniques SET collection_category_id=3, priority=69 WHERE id=359;
UPDATE collection_uniques SET collection_category_id=7, priority=112 WHERE id=360;
UPDATE collection_uniques SET collection_category_id=7, priority=81 WHERE id=361;
UPDATE collection_uniques SET collection_category_id=1, priority=23 WHERE id=362;
UPDATE collection_uniques SET collection_category_id=4, priority=19 WHERE id=363;
UPDATE collection_uniques SET collection_category_id=7, priority=82 WHERE id=364;
UPDATE collection_uniques SET collection_category_id=7, priority=90 WHERE id=365;
UPDATE collection_uniques SET collection_category_id=4, priority=20 WHERE id=366;
UPDATE collection_uniques SET collection_category_id=2, priority=29 WHERE id=367;
UPDATE collection_uniques SET collection_category_id=1, priority=50 WHERE id=368;
UPDATE collection_uniques SET collection_category_id=7, priority=20 WHERE id=369;
UPDATE collection_uniques SET collection_category_id=2, priority=25 WHERE id=370;
UPDATE collection_uniques SET collection_category_id=2, priority=24 WHERE id=371;
UPDATE collection_uniques SET collection_category_id=6, priority=2 WHERE id=372;
UPDATE collection_uniques SET collection_category_id=6, priority=1 WHERE id=373;
UPDATE collection_uniques SET collection_category_id=2, priority=21 WHERE id=374;
UPDATE collection_uniques SET collection_category_id=4, priority=2 WHERE id=375;
UPDATE collection_uniques SET collection_category_id=4, priority=1 WHERE id=376;
UPDATE collection_uniques SET collection_category_id=7, priority=117 WHERE id=377;
UPDATE collection_uniques SET collection_category_id=2, priority=12 WHERE id=378;
UPDATE collection_uniques SET collection_category_id=1, priority=18 WHERE id=379;
UPDATE collection_uniques SET collection_category_id=1, priority=120 WHERE id=380;
UPDATE collection_uniques SET collection_category_id=5, priority=21 WHERE id=381;
UPDATE collection_uniques SET collection_category_id=1, priority=36 WHERE id=382;
UPDATE collection_uniques SET collection_category_id=1, priority=80 WHERE id=383;
UPDATE collection_uniques SET collection_category_id=1, priority=90 WHERE id=384;
UPDATE collection_uniques SET collection_category_id=1, priority=100 WHERE id=385;
UPDATE collection_uniques SET collection_category_id=3, priority=14 WHERE id=386;
UPDATE collection_uniques SET collection_category_id=1, priority=17 WHERE id=387;
UPDATE collection_uniques SET collection_category_id=7, priority=6 WHERE id=388;
UPDATE collection_uniques SET priority=47 WHERE id=389;
UPDATE collection_uniques SET collection_category_id=8, priority=3 WHERE id=390;
UPDATE collection_uniques SET collection_category_id=7, priority=99 WHERE id=391;
UPDATE collection_uniques SET priority=19 WHERE id=392;
UPDATE collection_uniques SET collection_category_id=1, priority=40 WHERE id=393;
UPDATE collection_uniques SET priority=58 WHERE id=394;
UPDATE collection_uniques SET collection_category_id=7, priority=72 WHERE id=395;
UPDATE collection_uniques SET collection_category_id=7, priority=66 WHERE id=396;
UPDATE collection_uniques SET collection_category_id=7, priority=34 WHERE id=397;
UPDATE collection_uniques SET collection_category_id=7, priority=114 WHERE id=398;
UPDATE collection_uniques SET collection_category_id=2, priority=38 WHERE id=399;
UPDATE collection_uniques SET collection_category_id=2, priority=41 WHERE id=400;
UPDATE collection_uniques SET collection_category_id=1, priority=46 WHERE id=401;
UPDATE collection_uniques SET collection_category_id=1, priority=43 WHERE id=402;
UPDATE collection_uniques SET collection_category_id=2, priority=6 WHERE id=403;
UPDATE collection_uniques SET collection_category_id=9, priority=6 WHERE id=404;
UPDATE collection_uniques SET collection_category_id=7, priority=16 WHERE id=405;
UPDATE collection_uniques SET collection_category_id=7, priority=14 WHERE id=406;
UPDATE collection_uniques SET collection_category_id=7, priority=107 WHERE id=407;
UPDATE collection_uniques SET collection_category_id=7, priority=108 WHERE id=408;
UPDATE collection_uniques SET collection_category_id=1, priority=38 WHERE id=409;
UPDATE collection_uniques SET priority=20 WHERE id=410;
UPDATE collection_uniques SET collection_category_id=3, priority=67 WHERE id=411;
UPDATE collection_uniques SET collection_category_id=8, priority=8 WHERE id=412;
UPDATE collection_uniques SET collection_category_id=7, priority=92 WHERE id=413;
UPDATE collection_uniques SET priority=45 WHERE id=414;
UPDATE collection_uniques SET priority=42 WHERE id=415;
UPDATE collection_uniques SET collection_category_id=2, priority=27 WHERE id=416;
UPDATE collection_uniques SET collection_category_id=2, priority=26 WHERE id=417;
UPDATE collection_uniques SET priority=54 WHERE id=418;
UPDATE collection_uniques SET collection_category_id=8, priority=13 WHERE id=419;
UPDATE collection_uniques SET collection_category_id=7, priority=132 WHERE id=420;
UPDATE collection_uniques SET collection_category_id=8, priority=16 WHERE id=421;
UPDATE collection_uniques SET priority=59 WHERE id=422;
UPDATE collection_uniques SET collection_category_id=7, priority=104 WHERE id=423;
UPDATE collection_uniques SET collection_category_id=1, priority=22 WHERE id=424;
UPDATE collection_uniques SET collection_category_id=7, priority=110 WHERE id=425;
UPDATE collection_uniques SET collection_category_id=7, priority=88 WHERE id=426;
UPDATE collection_uniques SET collection_category_id=3, priority=23 WHERE id=427;
UPDATE collection_uniques SET collection_category_id=3, priority=22 WHERE id=428;
UPDATE collection_uniques SET collection_category_id=3, priority=66 WHERE id=430;
UPDATE collection_uniques SET collection_category_id=3, priority=11 WHERE id=431;
UPDATE collection_uniques SET collection_category_id=5, priority=1 WHERE id=432;
UPDATE collection_uniques SET collection_category_id=1, priority=52 WHERE id=433;
UPDATE collection_uniques SET collection_category_id=3, priority=17 WHERE id=434;
UPDATE collection_uniques SET priority=210 WHERE id=435;
UPDATE collection_uniques SET priority=200 WHERE id=436;
UPDATE collection_uniques SET collection_category_id=7, priority=131 WHERE id=437;
UPDATE collection_uniques SET collection_category_id=3, priority=18 WHERE id=438;
UPDATE collection_uniques SET priority=43 WHERE id=439;
UPDATE collection_uniques SET collection_category_id=8, priority=9 WHERE id=440;
UPDATE collection_uniques SET collection_category_id=5, priority=25 WHERE id=441;
UPDATE collection_uniques SET priority=41 WHERE id=442;
UPDATE collection_uniques SET collection_category_id=7, priority=39 WHERE id=443;
UPDATE collection_uniques SET collection_category_id=7, priority=47 WHERE id=444;
UPDATE collection_uniques SET collection_category_id=5, priority=4 WHERE id=445;
UPDATE collection_uniques SET collection_category_id=1, priority=65 WHERE id=446;
UPDATE collection_uniques SET collection_category_id=7, priority=8 WHERE id=447;
UPDATE collection_uniques SET priority=1 WHERE id=448;
UPDATE collection_uniques SET collection_category_id=7, priority=24 WHERE id=449;
UPDATE collection_uniques SET collection_category_id=7, priority=56 WHERE id=450;
UPDATE collection_uniques SET collection_category_id=1, priority=4 WHERE id=451;
UPDATE collection_uniques SET collection_category_id=7, priority=58 WHERE id=452;
UPDATE collection_uniques SET collection_category_id=3, priority=34 WHERE id=453;
UPDATE collection_uniques SET collection_category_id=2, priority=5 WHERE id=454;
UPDATE collection_uniques SET collection_category_id=7, priority=118 WHERE id=455;
UPDATE collection_uniques SET collection_category_id=3, priority=24 WHERE id=456;
UPDATE collection_uniques SET collection_category_id=8, priority=15 WHERE id=457;
UPDATE collection_uniques SET collection_category_id=3, priority=57 WHERE id=458;
UPDATE collection_uniques SET collection_category_id=2, priority=20 WHERE id=459;
UPDATE collection_uniques SET collection_category_id=1, priority=70 WHERE id=460;
UPDATE collection_uniques SET priority=44 WHERE id=461;
UPDATE collection_uniques SET collection_category_id=7, priority=27 WHERE id=469;
COMMIT TRANSACTION;
PRAGMA optimize;
PRAGMA synchronous = NORMAL;
PRAGMA journal_mode = DELETE;
PRAGMA shrink_memory;
